services:
  web:
    build: .
    container_name: cancer-prediction-web
    command: gunicorn Capstone.wsgi:application --bind 0.0.0.0:8000 --workers 3 --timeout 120
    volumes:
      - .:/app
      - static_volume:/app/static
    expose:
      - "8000"
    networks:
      - app-network

  nginx:
    image: nginx:latest
    container_name: cancer-prediction-nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - ./nginx/certbot:/etc/nginx/certbot
      - static_volume:/app/static
      - ./nginx/ssl:/etc/letsencrypt
      - ./nginx/logs:/var/log/nginx
    depends_on:
      - web
    networks:
      - app-network

  certbot:
    image: certbot/certbot
    container_name: certbot
    volumes:
      - ./nginx/certbot:/var/www/certbot
      - ./nginx/ssl:/etc/letsencrypt
    entrypoint: "/bin/sh -c 'trap exit TERM; while :; do certbot renew; sleep 12h & wait $${!}; done;'"
    depends_on:
      - nginx
    networks:
      - app-network

volumes:
  static_volume:

networks:
  app-network:
    driver: bridge
